### ISSUE TITLE
vs 2019 (16.2.3): An exception of type ImportCardinalityMismatchException has been encountered

### ISSUE THREAD

**Issue by ChaoJia** [kaby76/AntlrVSIX#12]
Hi,
it seems this extension has been causing an exception recently on Windows 10 VS 2019. 
Log:

```
...
  <entry>
    <record>587</record>
    <time>2019/08/30 09:43:54.483</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ComponentModel.Composition.ImportCardinalityMismatchException: Duplicate EditorFormatDefinition exports with identical name attributes exist. Duplicate name is suggestion</description>
  </entry>
...
```
The error disappears if I disable this extension. 

A list of all the extensions I've installed:
AntlrVSIX
Live Share [Disabled]
Test Adapter for Google Test
Test Adapter for Boost.Test
Developer Analytics Tools
Visual Studio IntelliCode
Dotnet Extensions for Test Explorer

Could you please look into it? Thanks.

**Comment by kaby76** [comment]
Thanks! Fixed in v3.0.2.
