### ISSUE TITLE
Options window not working

### ISSUE THREAD

**Issue by nvierge** [kaby76/AntlrVSIX#38]
The options window was not working for me. I investigate some time before i find the problem: my variable HOMEPATH is set to "\\" by my organization. If i force it to a standard value, it works.
In my opinion, you should not rely on the variable HOMEPATH in the Option class.

if i replace this line
`private static readonly string home = System.Environment.GetEnvironmentVariable("HOMEPATH");
`
with this line:
`private static readonly string home = System.Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);`
 it works for me and does not rely on HOMEPATH.

**Comment by kaby76** [comment]
Seems a reasonable request...will do. --K

**Comment by kaby76** [comment]
https://github.com/kaby76/AntlrVSIX/commit/81a1c8befc10fd1c33150215d079dd32329d2649#diff-0f28ee97d204f545e4077660d199d6b6

**Comment by kaby76** [comment]
Version 7.2 should take care of this problem as well. Let me know if that works for you.  --Ken

**Comment by nvierge** [comment]
The new version works well for me.
Thank you for your reactivity.
