### ISSUE TITLE
Links to User Guide and Documentation are broken

### ISSUE THREAD

**Issue by Oopsnut2** [kaby76/AntlrVSIX#97]
The Link to User Guide and Documentation on the Visual Studio MarketPlace lead to a non-existent page.

**Comment by kaby76** [comment]
@Oopsnut2 Thanks. I will fix it. I've been copying the [readme.md](https://github.com/kaby76/AntlrVSIX/blob/master/README.md) from the Github repo to the Marketplace (both VS2019 and VSCode), but I forgot that I can't use relative links for the top-level readme page. Any links it contains should be "absolute" to the Github repo for further content. --Ken

**Comment by kaby76** [comment]
Replacing copy of readme.md in vscode with symbolic link. https://github.com/kaby76/AntlrVSIX/commit/7d7efd279321712ad7246749ee964903f1f4695f

**Comment by Oopsnut2** [comment]
Thank you!

Ed Nicholas
President, Nicholas Simulation Services LLC
(540) 246-3393

**Comment by kaby76** [comment]
Fixed in 8.2.
